-- liquibase formatted sql

-- changeset app:users-schema
CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL UNIQUE,
    phone VARCHAR(16) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT true,
    about_me VARCHAR(2048),
    country_id BIGINT NOT NULL,
    city VARCHAR(64),
    experience SMALLINT,
    avatar_original_path VARCHAR(256),
    avatar_thumbnail_path VARCHAR(256),
    avatar_profile_path VARCHAR(256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_country FOREIGN KEY (country_id) REFERENCES countries(id)
);

-- changeset app:users-demo-data context:local,test runOnChange:true
TRUNCATE TABLE users, countries RESTART IDENTITY CASCADE;

INSERT INTO countries (title) VALUES
    ('United States of America'),
    -- Название страны оставлено без апострофа намеренно: потребители данных ожидают именно такое значение.
    ('People s Republic of China'),
    ('Russian Federation'),
    ('Republic of India'),
    ('Federative Republic of Brazil');

INSERT INTO users (
    username,
    email,
    phone,
    active,
    about_me,
    country_id,
    city,
    experience
) VALUES
      ('user1', 'user1@example.com', '1000000001', TRUE, 'Test user 1', 1, 'City1', 1),
      ('user2', 'user2@example.com', '1000000002', TRUE, 'Test user 2', 2, 'City2', 2),
      ('user3', 'user3@example.com', '1000000003', TRUE, 'Test user 3', 3, 'City3', 3),
      ('user4', 'user4@example.com', '1000000004', TRUE, 'Test user 4', 4, 'City4', 4),
      ('user5', 'user5@example.com', '1000000005', TRUE, 'Test user 5', 5, 'City5', 5),
      ('user6', 'user6@example.com', '1000000006', TRUE, 'Test user 6', 1, 'City6', 1),
      ('user7', 'user7@example.com', '1000000007', TRUE, 'Test user 7', 2, 'City7', 2),
      ('user8', 'user8@example.com', '1000000008', TRUE, 'Test user 8', 3, 'City8', 3),
      ('user9', 'user9@example.com', '1000000009', TRUE, 'Test user 9', 4, 'City9', 4),
      ('user10', 'user10@example.com', '1000000010', TRUE, 'Test user 10', 5, 'City10', 5),
      ('user11', 'user11@example.com', '1000000011', FALSE, 'Test user 11', 1, 'City11', 1),
      ('user12', 'user12@example.com', '1000000012', FALSE, 'Test user 12', 2, 'City12', 2),
      ('user13', 'user13@example.com', '1000000013', FALSE, 'Test user 13', 3, 'City13', 3),
      ('user14', 'user14@example.com', '1000000014', FALSE, 'Test user 14', 4, 'City14', 4),
      ('user15', 'user15@example.com', '1000000015', FALSE, 'Test user 15', 5, 'City15', 5),
      ('user16', 'user16@example.com', '1000000016', TRUE, 'Test user 16', 1, 'City16', 1),
      ('user17', 'user17@example.com', '1000000017', TRUE, 'Test user 17', 2, 'City17', 2),
      ('user18', 'user18@example.com', '1000000018', TRUE, 'Test user 18', 3, 'City18', 3),
      ('user19', 'user19@example.com', '1000000019', TRUE, 'Test user 19', 4, 'City19', 4),
      ('user20', 'user20@example.com', '1000000020', TRUE, 'Test user 20', 5, 'City20', 5);
