CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL UNIQUE,
    phone VARCHAR(16) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    about_me VARCHAR(2048),
    country_id BIGINT NOT NULL,
    city VARCHAR(64),
    experience SMALLINT,
    profile_picture_file_id VARCHAR(256),
    profile_picture_small_file_id VARCHAR(256),
    profile_picture_medium_file_id VARCHAR(256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_country FOREIGN KEY (country_id) REFERENCES countries(id)
);

INSERT INTO countries (title) VALUES
    ('United States of America'),
    ('People s Republic of China'),
    ('Russian Federation'),
    ('Republic of India'),
    ('Federative Republic of Brazil');

INSERT INTO users (
    username,
    email,
    phone,
    password,
    active,
    about_me,
    country_id,
    city,
    experience
) VALUES
      ('user1', 'user1@example.com', '1000000001', 'password1', TRUE, 'Test user 1', 1, 'City1', 1),
      ('user2', 'user2@example.com', '1000000002', 'password2', TRUE, 'Test user 2', 2, 'City2', 2),
      ('user3', 'user3@example.com', '1000000003', 'password3', TRUE, 'Test user 3', 3, 'City3', 3),
      ('user4', 'user4@example.com', '1000000004', 'password4', TRUE, 'Test user 4', 4, 'City4', 4),
      ('user5', 'user5@example.com', '1000000005', 'password5', TRUE, 'Test user 5', 5, 'City5', 5),
      ('user6', 'user6@example.com', '1000000006', 'password6', TRUE, 'Test user 6', 1, 'City6', 1),
      ('user7', 'user7@example.com', '1000000007', 'password7', TRUE, 'Test user 7', 2, 'City7', 2),
      ('user8', 'user8@example.com', '1000000008', 'password8', TRUE, 'Test user 8', 3, 'City8', 3),
      ('user9', 'user9@example.com', '1000000009', 'password9', TRUE, 'Test user 9', 4, 'City9', 4),
      ('user10', 'user10@example.com', '1000000010', 'password10', TRUE, 'Test user 10', 5, 'City10', 5),
      ('user11', 'user11@example.com', '1000000011', 'password11', FALSE, 'Test user 11', 1, 'City11', 1),
      ('user12', 'user12@example.com', '1000000012', 'password12', FALSE, 'Test user 12', 2, 'City12', 2),
      ('user13', 'user13@example.com', '1000000013', 'password13', FALSE, 'Test user 13', 3, 'City13', 3),
      ('user14', 'user14@example.com', '1000000014', 'password14', FALSE, 'Test user 14', 4, 'City14', 4),
      ('user15', 'user15@example.com', '1000000015', 'password15', FALSE, 'Test user 15', 5, 'City15', 5),
      ('user16', 'user16@example.com', '1000000016', 'password16', TRUE, 'Test user 16', 1, 'City16', 1),
      ('user17', 'user17@example.com', '1000000017', 'password17', TRUE, 'Test user 17', 2, 'City17', 2),
      ('user18', 'user18@example.com', '1000000018', 'password18', TRUE, 'Test user 18', 3, 'City18', 3),
      ('user19', 'user19@example.com', '1000000019', 'password19', TRUE, 'Test user 19', 4, 'City19', 4),
      ('user20', 'user20@example.com', '1000000020', 'password20', TRUE, 'Test user 20', 5, 'City20', 5);
